import java.io.FileReader;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;

import java.util.TreeMap;
import java.util.Map;

/**
 *
 * Project Part 1: Lexical Analyzer
 *
 * @author Sarah Winter, Marie Van Den Bogaard, Léo Exibard, Gilles Geeraerts
 *
 */

public class Main{
    /**
     *
     * The scanner
     *
     * @param args  The argument(s) given to the program
     * @throws IOException java.io.IOException if an I/O-Error occurs
     * @throws FileNotFoundException java.io.FileNotFoundException if the specified file does not exist
     *
     */
    public static void main(String[] args) throws FileNotFoundException, IOException, SecurityException{
        // Display the usage when the number of arguments is wrong (should be 1)
        if(args.length != 1){
            System.out.println("Usage:  java -jar part2.jar file.fs\n"
                             + "or\tjava "+Main.class.getSimpleName()+" file.fs");
            System.exit(0);
        }



        // Open the file given in argument
        FileReader source = new FileReader(args[0]);


        /**
         * The lexer generated by <a href="http://www.jflex.de/">JFlex</a>
         */
        //final LexicalAnalyzer analyzer = new LexicalAnalyzer(source);
        final Parser parser = new Parser(source);

        ParseTree parseTree = parser.Program();
        parser.printUsedRules();


        FileWriter outputFile = new FileWriter("more/tree.tex");
        outputFile.write(parseTree.toLaTeX());
        outputFile.close();

    }


}
